// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain_region_param_v1.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc;

public interface blockchain_region_spreading_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.blockchain_region_spreading_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helium.tagged_spreading tagged_spreading = 1;</code>
   */
  java.util.List<com.helium.grpc.tagged_spreading> 
      getTaggedSpreadingList();
  /**
   * <code>repeated .helium.tagged_spreading tagged_spreading = 1;</code>
   */
  com.helium.grpc.tagged_spreading getTaggedSpreading(int index);
  /**
   * <code>repeated .helium.tagged_spreading tagged_spreading = 1;</code>
   */
  int getTaggedSpreadingCount();
  /**
   * <code>repeated .helium.tagged_spreading tagged_spreading = 1;</code>
   */
  java.util.List<? extends com.helium.grpc.tagged_spreadingOrBuilder> 
      getTaggedSpreadingOrBuilderList();
  /**
   * <code>repeated .helium.tagged_spreading tagged_spreading = 1;</code>
   */
  com.helium.grpc.tagged_spreadingOrBuilder getTaggedSpreadingOrBuilder(
      int index);
}
