// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain_region_param_v1.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc;

/**
 * Protobuf type {@code helium.blockchain_region_params_v1}
 */
public final class blockchain_region_params_v1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helium.blockchain_region_params_v1)
    blockchain_region_params_v1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use blockchain_region_params_v1.newBuilder() to construct.
  private blockchain_region_params_v1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private blockchain_region_params_v1() {
    regionParams_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new blockchain_region_params_v1();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.helium.grpc.regionparam.internal_static_helium_blockchain_region_params_v1_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.helium.grpc.regionparam.internal_static_helium_blockchain_region_params_v1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.helium.grpc.blockchain_region_params_v1.class, com.helium.grpc.blockchain_region_params_v1.Builder.class);
  }

  public static final int REGION_PARAMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.helium.grpc.blockchain_region_param_v1> regionParams_;
  /**
   * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.helium.grpc.blockchain_region_param_v1> getRegionParamsList() {
    return regionParams_;
  }
  /**
   * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.helium.grpc.blockchain_region_param_v1OrBuilder> 
      getRegionParamsOrBuilderList() {
    return regionParams_;
  }
  /**
   * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
   */
  @java.lang.Override
  public int getRegionParamsCount() {
    return regionParams_.size();
  }
  /**
   * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
   */
  @java.lang.Override
  public com.helium.grpc.blockchain_region_param_v1 getRegionParams(int index) {
    return regionParams_.get(index);
  }
  /**
   * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
   */
  @java.lang.Override
  public com.helium.grpc.blockchain_region_param_v1OrBuilder getRegionParamsOrBuilder(
      int index) {
    return regionParams_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < regionParams_.size(); i++) {
      output.writeMessage(1, regionParams_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < regionParams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, regionParams_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.helium.grpc.blockchain_region_params_v1)) {
      return super.equals(obj);
    }
    com.helium.grpc.blockchain_region_params_v1 other = (com.helium.grpc.blockchain_region_params_v1) obj;

    if (!getRegionParamsList()
        .equals(other.getRegionParamsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRegionParamsCount() > 0) {
      hash = (37 * hash) + REGION_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getRegionParamsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.helium.grpc.blockchain_region_params_v1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.helium.grpc.blockchain_region_params_v1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.helium.grpc.blockchain_region_params_v1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.helium.grpc.blockchain_region_params_v1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helium.blockchain_region_params_v1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helium.blockchain_region_params_v1)
      com.helium.grpc.blockchain_region_params_v1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.helium.grpc.regionparam.internal_static_helium_blockchain_region_params_v1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.helium.grpc.regionparam.internal_static_helium_blockchain_region_params_v1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.helium.grpc.blockchain_region_params_v1.class, com.helium.grpc.blockchain_region_params_v1.Builder.class);
    }

    // Construct using com.helium.grpc.blockchain_region_params_v1.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (regionParamsBuilder_ == null) {
        regionParams_ = java.util.Collections.emptyList();
      } else {
        regionParams_ = null;
        regionParamsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.helium.grpc.regionparam.internal_static_helium_blockchain_region_params_v1_descriptor;
    }

    @java.lang.Override
    public com.helium.grpc.blockchain_region_params_v1 getDefaultInstanceForType() {
      return com.helium.grpc.blockchain_region_params_v1.getDefaultInstance();
    }

    @java.lang.Override
    public com.helium.grpc.blockchain_region_params_v1 build() {
      com.helium.grpc.blockchain_region_params_v1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.helium.grpc.blockchain_region_params_v1 buildPartial() {
      com.helium.grpc.blockchain_region_params_v1 result = new com.helium.grpc.blockchain_region_params_v1(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.helium.grpc.blockchain_region_params_v1 result) {
      if (regionParamsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          regionParams_ = java.util.Collections.unmodifiableList(regionParams_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.regionParams_ = regionParams_;
      } else {
        result.regionParams_ = regionParamsBuilder_.build();
      }
    }

    private void buildPartial0(com.helium.grpc.blockchain_region_params_v1 result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.helium.grpc.blockchain_region_params_v1) {
        return mergeFrom((com.helium.grpc.blockchain_region_params_v1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.helium.grpc.blockchain_region_params_v1 other) {
      if (other == com.helium.grpc.blockchain_region_params_v1.getDefaultInstance()) return this;
      if (regionParamsBuilder_ == null) {
        if (!other.regionParams_.isEmpty()) {
          if (regionParams_.isEmpty()) {
            regionParams_ = other.regionParams_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRegionParamsIsMutable();
            regionParams_.addAll(other.regionParams_);
          }
          onChanged();
        }
      } else {
        if (!other.regionParams_.isEmpty()) {
          if (regionParamsBuilder_.isEmpty()) {
            regionParamsBuilder_.dispose();
            regionParamsBuilder_ = null;
            regionParams_ = other.regionParams_;
            bitField0_ = (bitField0_ & ~0x00000001);
            regionParamsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRegionParamsFieldBuilder() : null;
          } else {
            regionParamsBuilder_.addAllMessages(other.regionParams_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.helium.grpc.blockchain_region_param_v1 m =
                  input.readMessage(
                      com.helium.grpc.blockchain_region_param_v1.parser(),
                      extensionRegistry);
              if (regionParamsBuilder_ == null) {
                ensureRegionParamsIsMutable();
                regionParams_.add(m);
              } else {
                regionParamsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.helium.grpc.blockchain_region_param_v1> regionParams_ =
      java.util.Collections.emptyList();
    private void ensureRegionParamsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        regionParams_ = new java.util.ArrayList<com.helium.grpc.blockchain_region_param_v1>(regionParams_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.helium.grpc.blockchain_region_param_v1, com.helium.grpc.blockchain_region_param_v1.Builder, com.helium.grpc.blockchain_region_param_v1OrBuilder> regionParamsBuilder_;

    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public java.util.List<com.helium.grpc.blockchain_region_param_v1> getRegionParamsList() {
      if (regionParamsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(regionParams_);
      } else {
        return regionParamsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public int getRegionParamsCount() {
      if (regionParamsBuilder_ == null) {
        return regionParams_.size();
      } else {
        return regionParamsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public com.helium.grpc.blockchain_region_param_v1 getRegionParams(int index) {
      if (regionParamsBuilder_ == null) {
        return regionParams_.get(index);
      } else {
        return regionParamsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder setRegionParams(
        int index, com.helium.grpc.blockchain_region_param_v1 value) {
      if (regionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionParamsIsMutable();
        regionParams_.set(index, value);
        onChanged();
      } else {
        regionParamsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder setRegionParams(
        int index, com.helium.grpc.blockchain_region_param_v1.Builder builderForValue) {
      if (regionParamsBuilder_ == null) {
        ensureRegionParamsIsMutable();
        regionParams_.set(index, builderForValue.build());
        onChanged();
      } else {
        regionParamsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder addRegionParams(com.helium.grpc.blockchain_region_param_v1 value) {
      if (regionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionParamsIsMutable();
        regionParams_.add(value);
        onChanged();
      } else {
        regionParamsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder addRegionParams(
        int index, com.helium.grpc.blockchain_region_param_v1 value) {
      if (regionParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRegionParamsIsMutable();
        regionParams_.add(index, value);
        onChanged();
      } else {
        regionParamsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder addRegionParams(
        com.helium.grpc.blockchain_region_param_v1.Builder builderForValue) {
      if (regionParamsBuilder_ == null) {
        ensureRegionParamsIsMutable();
        regionParams_.add(builderForValue.build());
        onChanged();
      } else {
        regionParamsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder addRegionParams(
        int index, com.helium.grpc.blockchain_region_param_v1.Builder builderForValue) {
      if (regionParamsBuilder_ == null) {
        ensureRegionParamsIsMutable();
        regionParams_.add(index, builderForValue.build());
        onChanged();
      } else {
        regionParamsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder addAllRegionParams(
        java.lang.Iterable<? extends com.helium.grpc.blockchain_region_param_v1> values) {
      if (regionParamsBuilder_ == null) {
        ensureRegionParamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, regionParams_);
        onChanged();
      } else {
        regionParamsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder clearRegionParams() {
      if (regionParamsBuilder_ == null) {
        regionParams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        regionParamsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public Builder removeRegionParams(int index) {
      if (regionParamsBuilder_ == null) {
        ensureRegionParamsIsMutable();
        regionParams_.remove(index);
        onChanged();
      } else {
        regionParamsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public com.helium.grpc.blockchain_region_param_v1.Builder getRegionParamsBuilder(
        int index) {
      return getRegionParamsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public com.helium.grpc.blockchain_region_param_v1OrBuilder getRegionParamsOrBuilder(
        int index) {
      if (regionParamsBuilder_ == null) {
        return regionParams_.get(index);  } else {
        return regionParamsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public java.util.List<? extends com.helium.grpc.blockchain_region_param_v1OrBuilder> 
         getRegionParamsOrBuilderList() {
      if (regionParamsBuilder_ != null) {
        return regionParamsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(regionParams_);
      }
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public com.helium.grpc.blockchain_region_param_v1.Builder addRegionParamsBuilder() {
      return getRegionParamsFieldBuilder().addBuilder(
          com.helium.grpc.blockchain_region_param_v1.getDefaultInstance());
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public com.helium.grpc.blockchain_region_param_v1.Builder addRegionParamsBuilder(
        int index) {
      return getRegionParamsFieldBuilder().addBuilder(
          index, com.helium.grpc.blockchain_region_param_v1.getDefaultInstance());
    }
    /**
     * <code>repeated .helium.blockchain_region_param_v1 region_params = 1;</code>
     */
    public java.util.List<com.helium.grpc.blockchain_region_param_v1.Builder> 
         getRegionParamsBuilderList() {
      return getRegionParamsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.helium.grpc.blockchain_region_param_v1, com.helium.grpc.blockchain_region_param_v1.Builder, com.helium.grpc.blockchain_region_param_v1OrBuilder> 
        getRegionParamsFieldBuilder() {
      if (regionParamsBuilder_ == null) {
        regionParamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.helium.grpc.blockchain_region_param_v1, com.helium.grpc.blockchain_region_param_v1.Builder, com.helium.grpc.blockchain_region_param_v1OrBuilder>(
                regionParams_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        regionParams_ = null;
      }
      return regionParamsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helium.blockchain_region_params_v1)
  }

  // @@protoc_insertion_point(class_scope:helium.blockchain_region_params_v1)
  private static final com.helium.grpc.blockchain_region_params_v1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.helium.grpc.blockchain_region_params_v1();
  }

  public static com.helium.grpc.blockchain_region_params_v1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<blockchain_region_params_v1>
      PARSER = new com.google.protobuf.AbstractParser<blockchain_region_params_v1>() {
    @java.lang.Override
    public blockchain_region_params_v1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<blockchain_region_params_v1> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<blockchain_region_params_v1> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.helium.grpc.blockchain_region_params_v1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

