// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/iot_config.proto

// Protobuf Java Version: 3.25.1
package com.helium.grpc;

public interface protocol_gwmp_mapping_v1OrBuilder extends
    // @@protoc_insertion_point(interface_extends:helium.iot_config.protocol_gwmp_mapping_v1)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helium.region region = 1;</code>
   * @return The enum numeric value on the wire for region.
   */
  int getRegionValue();
  /**
   * <code>.helium.region region = 1;</code>
   * @return The region.
   */
  com.helium.grpc.region getRegion();

  /**
   * <code>uint32 port = 2;</code>
   * @return The port.
   */
  int getPort();
}
